@Movies.Api_HostAddress = http://localhost:5157
@Movie.Slug = harambae-2024
@Movie.Id = 680cc124-5d34-4085-9429-9db472e429ce

### Create Movies 
POST {{Movies.Api_HostAddress}}/api/movies
Accept: application/json
Content-Type: application/json

{
  "title": "HaradmBvae",
  "yearOfRelease": 2025,
  "genres": ["Comedy"]
}

### Get Movies
GET {{Movies.Api_HostAddress}}/api/movies
Accept: application/json

### Get Movie by id
GET {{Movies.Api_HostAddress}}/api/movies/{{Movie.Id}}

### Get Movie by slug
GET {{Movies.Api_HostAddress}}/api/movies/{{Movie.Slug}}

### Update Movie
PUT {{Movies.Api_HostAddress}}/api/movies/{{Movie.Id}}
Content-Type: application/json

{
  "title": "booo",
  "yearOfRelease": 2024,
  "genres": ["Horror"]
}

### Delete Movie 
DELETE {{Movies.Api_HostAddress}}/api/movies/{{Movie.Id}}